import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles.css";
import { StyledComponentsRegistry } from "./components/StyledComponentsRegistry";
import Header from "./components/Header/Header";
import { SoundProvider } from "./providers/SoundProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Joy of Next playground",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const formattedDate = Intl.DateTimeFormat("en-US", {
    dateStyle: "short",
    timeStyle: "medium",
  }).format();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SoundProvider>
          <Header />
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </SoundProvider>
        <footer>Page rendered on {formattedDate}</footer>
      </body>
    </html>
  );
}
